//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberShipMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public System.Guid IdTask { get; set; }
        public string IdTicket { get; set; }
        public System.DateTime Date { get; set; }
        public string Detail { get; set; }
        public decimal Hours { get; set; }
        public System.Guid IdProjectUser { get; set; }
        public bool Send { get; set; }
    
        public virtual ProjectUser ProjectUser { get; set; }
    }
}
